id: A65D0EC43
title: The Noble Incantation entitled ‘The Rituals for the Blue-Clad Vajrapāṇi’
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-03-01 06:07:29.993344
  last_modified_at: 2022-03-01 06:07:29.993347
