id: A65D0EC43
title: The Noble Dhāraṇī of The Supreme Accomplishment of Sitātapatrā Born from the
  Tathāgata’s Uṣṇīṣa, the Great Invincible Dispeller
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-03-01 06:07:29.991657
  last_modified_at: 2022-03-01 06:07:29.991660
