id: A65D0EC43
title: Vajravidāraṇa Dhāraṇī (Nyingma Version)
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-03-01 06:07:29.998964
  last_modified_at: 2022-03-01 06:07:29.998967
