id: A65D0EC43
title: The Sūtra of Boundless Life and Wisdom
type: translation
source_metadata:
  languages:
  - en
  - de
  - fr
  - bo
  datatype: PlainText
  created_at: 2022-03-01 06:07:29.997533
  last_modified_at: 2022-03-01 06:07:29.997536
