id: A65D0EC43
title: The Bodhisattva’s Confession of Downfalls (Nyingma Version)
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-03-01 06:07:29.976468
  last_modified_at: 2022-03-01 06:07:29.976475
