id: A65D0EC43
title: 'The King of Aspiration Prayers: Samantabhadra''s “Aspiration to Good Actions”
  (Zangchö Mönlam)'
type: translation
source_metadata:
  languages:
  - en
  - es
  - fr
  - pt
  - bo
  datatype: PlainText
  created_at: 2022-03-01 06:07:29.986733
  last_modified_at: 2022-03-01 06:07:29.986740
