id: A65D0EC43
title: The Dhāraṇī of Stream of Wealth (Vasudhārā)
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-03-01 06:07:29.978541
  last_modified_at: 2022-03-01 06:07:29.978549
